server:
  port: 6038

spring:
  datasource:
    password: Meshree
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  

